import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import 'toastify-js/src/toastify.css'
//
import { Toaster } from '~/components/ui/sonner'
import { NavigationGuardLayout } from '~/components/layouts/navigation-guard-layout'
import SessionProvider from '~/providers/session-provider'
import { TooltipProvider } from '~/components/ui/tooltip'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <TooltipProvider delayDuration={50}>
            <NavigationGuardLayout>{children}</NavigationGuardLayout>
          </TooltipProvider>
          <Toaster richColors closeButton position="bottom-center" />
        </SessionProvider>
      </body>
    </html>
  )
}
