export const posts: any[] = [
  {
    id: 'post-1',
    title: 'The Future of AI',
    status: 'published',
    author: 'Jane Doe',
    createdAt: '2024-09-15T09:00:00Z',
    slug: 'the-future-of-ai',
    categories: [
      {
        id: 'cat-1',
        title: 'AI',
        slug: 'ai',
        icon: 'Brain',
      },
    ],
    tags: [
      {
        id: 'tag-1',
        title: 'future',
        slug: 'future',
        description: 'Future trends',
      },
      {
        id: 'tag-2',
        title: 'trends',
        slug: 'trends',
        description: 'Trending topics',
      },
    ],
  },
  {
    id: 'post-2',
    title: 'Web Development Trends 2023',
    status: 'draft',
    author: 'John Smith',
    createdAt: '2024-09-20T14:30:00Z',
    slug: 'web-development-trends-2023',
    categories: [
      {
        id: 'cat-2',
        title: 'Web Development',
        slug: 'web-development',
        icon: 'Code',
      },
    ],
    tags: [
      {
        id: 'tag-2',
        title: 'trends',
        slug: 'trends',
        description: 'Trending topics',
      },
      {
        id: 'tag-3',
        title: 'web',
        slug: 'web',
        description: 'Web development',
      },
      {
        id: 'tag-4',
        title: 'frontend',
        slug: 'frontend',
        description: 'Frontend development',
      },
    ],
  },
  {
    id: 'post-3',
    title: 'Mastering React Hooks in 2024 the Right Way',
    status: 'published',
    author: 'Alice Johnson',
    createdAt: '2024-10-10T11:15:00Z',
    slug: 'mastering-react-hooks',
    categories: [
      {
        id: 'cat-2',
        title: 'Web Development',
        slug: 'web-development',
        icon: 'Code',
      },
    ],
    tags: [
      {
        id: 'tag-5',
        title: 'react',
        slug: 'react',
        description: 'React library',
      },
      {
        id: 'tag-6',
        title: 'hooks',
        slug: 'hooks',
        description: 'React hooks',
      },
    ],
  },
  {
    id: 'post-4',
    title: 'The Art of Code Review',
    status: 'archived',
    author: 'Bob Williams',
    createdAt: '2024-10-05T16:45:00Z',
    slug: 'the-art-of-code-review',
    categories: [
      {
        id: 'cat-3',
        title: 'Data Science',
        slug: 'data-science',
        icon: 'ChartBar',
      },
    ],
    tags: [
      {
        id: 'tag-2',
        title: 'trends',
        slug: 'trends',
        description: 'Trending topics',
      },
    ],
  },
  {
    id: 'post-5',
    title: 'Introduction to TypeScript',
    status: 'published',
    author: 'Emma Brown',
    createdAt: '2024-10-22T10:00:00Z',
    slug: 'introduction-to-typescript',
    categories: [
      {
        id: 'cat-4',
        title: 'Mobile Development',
        slug: 'mobile-development',
        icon: 'Phone',
      },
    ],
    tags: [
      {
        id: 'tag-7',
        title: 'typescript',
        slug: 'typescript',
        description: 'TypeScript language',
      },
      {
        id: 'tag-8',
        title: 'javascript',
        slug: 'javascript',
        description: 'JavaScript language',
      },
    ],
  },
  {
    id: 'post-6',
    title: 'Understanding JavaScript Closures',
    status: 'draft',
    author: 'Chris Green',
    createdAt: '2024-11-01T08:30:00Z',
    slug: 'understanding-javascript-closures',
    categories: [
      {
        id: 'cat-2',
        title: 'Web Development',
        slug: 'web-development',
        icon: 'Code',
      },
    ],
    tags: [
      {
        id: 'tag-8',
        title: 'javascript',
        slug: 'javascript',
        description: 'JavaScript language',
      },
      {
        id: 'tag-9',
        title: 'closures',
        slug: 'closures',
        description: 'JavaScript closures',
      },
    ],
  },
  {
    id: 'post-7',
    title: 'A Guide to CSS Grid',
    status: 'published',
    author: 'Patricia White',
    createdAt: '2024-11-15T12:00:00Z',
    slug: 'a-guide-to-css-grid',
    categories: [
      {
        id: 'cat-2',
        title: 'Web Development',
        slug: 'web-development',
        icon: 'Code',
      },
    ],
    tags: [
      {
        id: 'tag-10',
        title: 'css',
        slug: 'css',
        description: 'CSS language',
      },
      {
        id: 'tag-11',
        title: 'grid',
        slug: 'grid',
        description: 'CSS Grid layout',
      },
    ],
  },
  {
    id: 'post-8',
    title: 'Building RESTful APIs with Node.js',
    status: 'archived',
    author: 'Michael Black',
    createdAt: '2024-11-10T09:45:00Z',
    slug: 'building-restful-apis-with-node-js',
    categories: [
      {
        id: 'cat-5',
        title: 'Cloud Computing',
        slug: 'cloud-computing',
        icon: 'Cloud',
      },
    ],
    tags: [
      {
        id: 'tag-12',
        title: 'node.js',
        slug: 'node.js',
        description: 'Node.js runtime',
      },
      {
        id: 'tag-13',
        title: 'restful',
        slug: 'restful',
        description: 'RESTful APIs',
      },
    ],
  },
  {
    id: 'post-9',
    title: 'State Management in Vue.js',
    status: 'published',
    author: 'Laura Blue',
    createdAt: '2024-09-05T14:20:00Z',
    slug: 'state-management-in-vue-js',
    categories: [
      {
        id: 'cat-2',
        title: 'Web Development',
        slug: 'web-development',
        icon: 'Code',
      },
    ],
    tags: [
      {
        id: 'tag-14',
        title: 'vue.js',
        slug: 'vue.js',
        description: 'Vue.js framework',
      },
      {
        id: 'tag-15',
        title: 'state management',
        slug: 'state-management',
        description: 'State management',
      },
    ],
  },
  {
    id: 'post-10',
    title: 'Exploring GraphQL',
    status: 'draft',
    author: 'Kevin Yellow',
    createdAt: '2024-10-01T11:10:00Z',
    slug: 'exploring-graphql',
    categories: [
      {
        id: 'cat-3',
        title: 'Data Science',
        slug: 'data-science',
        icon: 'ChartBar',
      },
    ],
    tags: [
      {
        id: 'tag-16',
        title: 'graphql',
        slug: 'graphql',
        description: 'GraphQL query language',
      },
      {
        id: 'tag-13',
        title: 'api',
        slug: 'api',
        description: 'APIs',
      },
    ],
  },
  {
    id: 'post-11',
    title: 'Advanced TypeScript Techniques',
    status: 'published',
    author: 'Nancy Red',
    createdAt: '2024-09-15T13:30:00Z',
    slug: 'advanced-typescript-techniques',
    categories: [
      {
        id: 'cat-4',
        title: 'Mobile Development',
        slug: 'mobile-development',
        icon: 'Phone',
      },
    ],
    tags: [
      {
        id: 'tag-7',
        title: 'typescript',
        slug: 'typescript',
        description: 'TypeScript language',
      },
      {
        id: 'tag-8',
        title: 'javascript',
        slug: 'javascript',
        description: 'JavaScript language',
      },
    ],
  },
  {
    id: 'post-12',
    title: 'Introduction to WebAssembly',
    status: 'archived',
    author: 'Oscar Purple',
    createdAt: '2024-10-01T10:00:00Z',
    slug: 'introduction-to-webassembly',
    categories: [
      {
        id: 'cat-2',
        title: 'Web Development',
        slug: 'web-development',
        icon: 'Code',
      },
    ],
    tags: [
      {
        id: 'tag-17',
        title: 'webassembly',
        slug: 'webassembly',
        description: 'WebAssembly technology',
      },
      {
        id: 'tag-2',
        title: 'web development',
        slug: 'web-development',
        description: 'Web development',
      },
    ],
  },
  {
    id: 'post-13',
    title: 'Building Mobile Apps with React Native',
    status: 'published',
    author: 'Paul Orange',
    createdAt: '2024-11-20T15:45:00Z',
    slug: 'building-mobile-apps-with-react-native',
    categories: [
      {
        id: 'cat-4',
        title: 'Mobile Development',
        slug: 'mobile-development',
        icon: 'Phone',
      },
    ],
    tags: [
      {
        id: 'tag-18',
        title: 'react native',
        slug: 'react-native',
        description: 'React Native framework',
      },
      {
        id: 'tag-19',
        title: 'mobile development',
        slug: 'mobile-development',
        description: 'Mobile development',
      },
    ],
  },
  {
    id: 'post-14',
    title: 'Serverless Architecture Explained',
    status: 'draft',
    author: 'Quincy Pink',
    createdAt: '2024-11-05T09:30:00Z',
    slug: 'serverless-architecture-explained',
    categories: [
      {
        id: 'cat-5',
        title: 'Cloud Computing',
        slug: 'cloud-computing',
        icon: 'Cloud',
      },
    ],
    tags: [
      {
        id: 'tag-20',
        title: 'serverless',
        slug: 'serverless',
        description: 'Serverless architecture',
      },
      {
        id: 'tag-21',
        title: 'cloud computing',
        slug: 'cloud-computing',
        description: 'Cloud computing',
      },
    ],
  },
  {
    id: 'post-15',
    title: 'Getting Started with Docker',
    status: 'published',
    author: 'Rachel Gray',
    createdAt: '2024-11-25T12:15:00Z',
    slug: 'getting-started-with-docker',
    categories: [
      {
        id: 'cat-5',
        title: 'Cloud Computing',
        slug: 'cloud-computing',
        icon: 'Cloud',
      },
    ],
    tags: [
      {
        id: 'tag-22',
        title: 'docker',
        slug: 'docker',
        description: 'Docker technology',
      },
      {
        id: 'tag-23',
        title: 'devops',
        slug: 'devops',
        description: 'DevOps practices',
      },
    ],
  },
]

export const categories: any[] = [
  {
    id: 'cat-1',
    title: 'AI',
    slug: 'ai',
    icon: 'Brain',
  },
  {
    id: 'cat-2',
    title: 'Web Development',
    slug: 'web-development',
    icon: 'Code',
  },
  {
    id: 'cat-3',
    title: 'Data Science',
    slug: 'data-science',
    icon: 'ChartBar',
  },
  {
    id: 'cat-4',
    title: 'Mobile Development',
    slug: 'mobile-development',
    icon: 'Phone',
  },
  {
    id: 'cat-5',
    title: 'Cloud Computing',
    slug: 'cloud-computing',
    icon: 'Cloud',
  },
]

export const tags = [
  {
    id: 'tag-1',
    title: 'future',
    slug: 'future',
    description: 'Future trends',
    posts: ['post-1'],
  },
  {
    id: 'tag-2',
    title: 'trends',
    slug: 'trends',
    description: 'Trending topics',
    posts: ['post-1', 'post-2', 'post-4'],
  },
  {
    id: 'tag-3',
    title: 'web',
    slug: 'web',
    description: 'Web development',
    posts: ['post-2'],
  },
  {
    id: 'tag-4',
    title: 'frontend',
    slug: 'frontend',
    description: 'Frontend development',
    posts: ['post-2'],
  },
  {
    id: 'tag-5',
    title: 'react',
    slug: 'react',
    description: 'React library',
    posts: ['post-3', 'post-11'],
  },
  {
    id: 'tag-6',
    title: 'hooks',
    slug: 'hooks',
    description: 'React hooks',
    posts: ['post-3'],
  },
  {
    id: 'tag-7',
    title: 'typescript',
    slug: 'typescript',
    description: 'TypeScript language',
    posts: ['post-5', 'post-11'],
  },
  {
    id: 'tag-8',
    title: 'javascript',
    slug: 'javascript',
    description: 'JavaScript language',
    posts: ['post-5', 'post-6', 'post-11'],
  },
  {
    id: 'tag-9',
    title: 'closures',
    slug: 'closures',
    description: 'JavaScript closures',
    posts: ['post-6'],
  },
  {
    id: 'tag-10',
    title: 'css',
    slug: 'css',
    description: 'CSS language',
    posts: ['post-7'],
  },
  {
    id: 'tag-11',
    title: 'grid',
    slug: 'grid',
    description: 'CSS Grid layout',
    posts: ['post-7'],
  },
  {
    id: 'tag-12',
    title: 'node.js',
    slug: 'node.js',
    description: 'Node.js runtime',
    posts: ['post-8'],
  },
  {
    id: 'tag-13',
    title: 'restful',
    slug: 'restful',
    description: 'RESTful APIs',
    posts: ['post-8'],
  },
  {
    id: 'tag-14',
    title: 'vue.js',
    slug: 'vue.js',
    description: 'Vue.js framework',
    posts: ['post-9'],
  },
  {
    id: 'tag-15',
    title: 'state management',
    slug: 'state-management',
    description: 'State management',
    posts: ['post-9'],
  },
  {
    id: 'tag-16',
    title: 'graphql',
    slug: 'graphql',
    description: 'GraphQL query language',
    posts: ['post-10'],
  },
  {
    id: 'tag-17',
    title: 'webassembly',
    slug: 'webassembly',
    description: 'WebAssembly technology',
    posts: ['post-12'],
  },
  {
    id: 'tag-18',
    title: 'react native',
    slug: 'react-native',
    description: 'React Native framework',
    posts: ['post-13'],
  },
  {
    id: 'tag-19',
    title: 'mobile development',
    slug: 'mobile-development',
    description: 'Mobile development',
    posts: ['post-13'],
  },
  {
    id: 'tag-20',
    title: 'serverless',
    slug: 'serverless',
    description: 'Serverless architecture',
    posts: ['post-14'],
  },
  {
    id: 'tag-21',
    title: 'cloud computing',
    slug: 'cloud-computing',
    description: 'Cloud computing',
    posts: ['post-14'],
  },
  {
    id: 'tag-22',
    title: 'docker',
    slug: 'docker',
    description: 'Docker technology',
    posts: ['post-15'],
  },
  {
    id: 'tag-23',
    title: 'devops',
    slug: 'devops',
    description: 'DevOps practices',
    posts: ['post-15'],
  },
]
